career_find/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'career_find'

urlpatterns = [
    path('', views.index , name = 'index'),
    url(r'result/(?P<page_num>\d+)/', views.result , name = 'result'),
    url(r'result/(?P<check_box>.+)/(?P<page_num>\d+)/', views.page , name = 'page')
    # url(r'no_req/(?P<page_num>\d+)/', no_req , name = 'no_req')
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import login

from . import views

app_name = 'users'
urlpatterns = [
    # Login page.
    path('login/', login, {'template_name': 'users/login.html'},
        name='login'),
        
    # # Logout page.
    # path('logout/', views.logout_view, name='logout'),
    
    # # Registration page. 
    # path('register/', views.register, name='register'),
]

career_find/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group_id = models.IntegerField()
    permission_id = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'


class AuthPermission(models.Model):
    name = models.CharField(max_length=50)
    content_type_id = models.IntegerField()
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField()
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=30)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=75)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user_id = models.IntegerField()
    group_id = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'auth_user_groups'


class AuthUserUserPermissions(models.Model):
    user_id = models.IntegerField()
    permission_id = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'


class DjangoContentType(models.Model):
    name = models.CharField(max_length=100)
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class MainTable(models.Model):
    地区 = models.CharField(max_length=100, blank=True, null=True)
    学校代码 = models.CharField(max_length=100, blank=True, null=True)
    学校名称 = models.CharField(max_length=100, blank=True, null=True)
    层次 = models.CharField(max_length=100, blank=True, null=True)
    专业类别 = models.CharField(max_length=200, blank=True, null=True)
    专业 = models.CharField(max_length=500, blank=True, null=True)
    科目要求 = models.CharField(max_length=200, blank=True, null=True)
    学校网站 = models.CharField(max_length=500, blank=True, null=True)
    sub_type = models.IntegerField(blank=True, null=True)
    sub = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'main_table'

career_find/forms.py
from django import forms

# ACTIVITY_STYLE = (("a", "地理"), ("b", "化学"), ("c", "历史"), ('d', '生物'), ('e', '物理'), ('f', '政治'))
# class HobbiesForm(forms.Form):  
#     hobbies = forms.MultipleChoiceField(label='sa', choices=ACTIVITY_STYLE, widget=forms.CheckboxSelectMultiple())
#print(HobbiesForm(data={"hobbies": ["a", "b", "c"]}).as_p())
#print(HobbiesForm(data={"hobbies": ["b", "c"]}).as_p())

class PageHop(forms.Form):
    跳页 = forms.IntegerField(label='',required=True)
    # def clean(self):
    # 	page_num = self.cleaned_data['跳页']
    # 	if page_num < 1 :
    # 		raise forms.ValidationError("请输入合理的页数")
    # 	return self.cleaned_data
    # class Meta:
    # 	labels = {'text': ''}
    # 	field = {'length':2}
    # def save(self):
    #     if not self.跳页:
    #         return            

    #     super(PageHop, self).save()
        

career_find/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect 
from django.urls import reverse
from .models import MainTable
from itertools import chain
from django.core.paginator import Paginator
from django.views.decorators.cache import cache_page
from django.contrib.auth.decorators import login_required
# Create your views here.
# coding:utf-8
from django.http import HttpResponse
from .forms import PageHop



def get_pages(totalpage=1,current_page=1):
    """
    example: get_pages(10,1) result=[1,2,3,4,5]
    example: get_pages(10,9) result=[6,7,8,9,10]
    页码个数由WEB_DISPLAY_PAGE设定
    """
    WEB_DISPLAY_PAGE = 16
    front_offset = int(WEB_DISPLAY_PAGE / 2)
    if WEB_DISPLAY_PAGE % 2 == 1:
        behind_offset=front_offset
    else:
        behind_offset=front_offset -1

    if totalpage < WEB_DISPLAY_PAGE:
        return list(range(1,totalpage+1))
    elif current_page<=front_offset:
        return list(range(1,WEB_DISPLAY_PAGE+1))
    elif current_page>=totalpage-behind_offset:
        start_page=totalpage-WEB_DISPLAY_PAGE+1
        return list(range(start_page,totalpage+1))
    else:
        start_page=current_page-front_offset
        end_page=current_page+behind_offset
        return list(range(start_page,end_page+1))


@login_required
def index(request):
#    if request.method != 'POST':
    return render(request, 'career_find/index.html')
## 未提交数据:创建一个新表单 
#        form = HobbiesForm()
#    else:
#    # POST提交的数据,对数据进行处理
#    else:
##        check_box = request.POST.getlist('check_box_list')
##        print(check_box)
#        return HttpResponseRedirect(reverse('career_find:result'))
#    
##    context = {'form': form}

#@cache_page(60 * 15)
@login_required
def result(request,page_num):
    form = PageHop()
    if request.method == 'POST':
        check_box = request.POST.getlist('check_box_list')
        
        dic_list = MainTable.objects.exclude(科目要求='不提科目要求').values()
        dic_list = list(dic_list)
        dic_list2 = dic_list[:]
#        find_result = dic_list
        check_string = ','.join(check_box)
        
        for dic in dic_list2:
            dic.setdefault('coin', 0)
            sub_string = dic['sub'].replace('，',',')
            
            if dic['sub_type'] == 1 and check_string.find(sub_string) < 0:
                dic_list.remove(dic)
                continue
            
            sub_list = sub_string.split(',')

            for sub in sub_list:
                if sub in check_box:
                    dic['coin'] += 1


            if dic['coin'] == 0:
                dic_list.remove(dic)
                
        find_result = dic_list
        find_result = sorted(dic_list,key = lambda x:(x['coin'],x['sub_type'],-len(x['层次'])),reverse=True)
        
#        find_result1 = MainTable.objects.filter(sub_type=0,sub__regex=r'%s|%s|%s'%(check_box[0],check_box[1],check_box[2])).order_by('科目要求')
#        sql = 'select * from main_table where (sub_type=1 and find_in_set(sub,"%s,%s,%s")) ORDER BY 科目要求 DESC'
#        find_result2 = MainTable.objects.raw(sql,params = check_box)
#        find_result = list(chain(find_result2,find_result1))
#        find_result = MainTable.objects.all()[:1]
        
        paginator = Paginator(find_result, 100)
#        page = request.POST.get('page')
        page = page_num
        contacts = paginator.page(page)
        check_box = ','.join(check_box)
        total_page_number=contacts.paginator.num_pages
        page_list=get_pages(int(total_page_number),int(page))
        context = {'contacts':contacts,'check_box':check_box,'page_list':page_list,'form':form}
        return render(request,'career_find/result.html',context)

        
#        return HttpResponseRedirect(reverse('career_find:result'))
#    
#    context = {'form': form}
#    return render(request, 'career_find/index.html', context)

#@cache_page(60 * 15)
@login_required
def page(request,check_box,page_num):
    form = PageHop()
    if request.method == 'POST':
        form = PageHop(request.POST)
        if form.is_valid():
            page_num = form.cleaned_data['跳页']
            
    if check_box == '不限':
            dic_list = MainTable.objects.filter(科目要求='不提科目要求')
            find_result = dic_list
            paginator = Paginator(find_result, 100)
            page = page_num
            contacts = paginator.page(page)
            total_page_number=contacts.paginator.num_pages
            page_list=get_pages(int(total_page_number),int(page))
            context = {'contacts':contacts,'check_box':check_box,'page_list':page_list,'form':form}
            return render(request,'career_find/result.html',context)
    
            
    else:
        check_box = check_box.split(',')
    #    find_result1 = MainTable.objects.filter(sub_type=0,sub__regex=r'%s|%s|%s'%(check_box[0],check_box[1],check_box[2]))
    #    sql = 'select * from main_table where (sub_type=1 and find_in_set(sub,"%s,%s,%s")) ORDER BY 科目要求 DESC'%(check_box[0],check_box[1],check_box[2])
    #    find_result2 = MainTable.objects.raw(sql)
    #    find_result = list(chain(find_result2,find_result1))
        
        dic_list = MainTable.objects.exclude(科目要求='不提科目要求').values()
        dic_list = list(dic_list)
        dic_list2 = dic_list[:]
        
        check_string = ','.join(check_box)
            
        for dic in dic_list2:
            dic.setdefault('coin', 0)
            sub_string = dic['sub'].replace('，',',')
            
            if dic['sub_type'] == 1 and check_string.find(sub_string) < 0:
                dic_list.remove(dic)
                continue
            
            sub_list = sub_string.split(',')
    
            for sub in sub_list:
                if sub in check_box:
                    dic['coin'] += 1
    
    
            if dic['coin'] == 0:
                dic_list.remove(dic)
                
        find_result = dic_list
        find_result = sorted(dic_list,key = lambda x:(x['coin'],x['sub_type']),reverse=True)
        
        
        paginator = Paginator(find_result, 100)
        page = page_num
        contacts = paginator.page(page)
        check_box = ','.join(check_box)
        total_page_number=contacts.paginator.num_pages
        page_list=get_pages(int(total_page_number),int(page))
        context = {'contacts':contacts,'check_box':check_box,'page_list':page_list,'form':form}
        return render(request,'career_find/result.html',context)
    

    
    
    
    
    
    
    
    

career_find/templates/career_find/index.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <style type="text/css">
        /*li {display:inline;font-family:"Times New Roman", Times, serif;
        font-size: 60px;}*/
        /*button {display:inline;}
        [name=check_box_list] {font-family:"Times New Roman", Times, serif;
                                font-size: 60px;}*/
        #fz {font-size: 20px;}
    </style>
    <script type="text/javascript">

	function test_ck( n ) {
	for ( var i = 0; i < n.check_box_list.length; ++i ) {
	if ( n.check_box_list[i].checked == true ) return true;
	}
	alert( '没有任何选项被选中' );
	return false;
	}



          function display_alert()
            {
              alert("I am an alert box!!")
            }
	</script>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>

    <!-- <form action="{% url 'career_find:result' 1%}" onsubmit='return test_ck(this)' method="post">
        
    	{% csrf_token %}
        请选择你的科目：
        <input type="checkbox" value="化学" name="check_box_list"/>化学

    	<input type="checkbox" value="历史" name="check_box_list"/>历史

    	<input type="checkbox" value="地理" name="check_box_list"/>地理

    	<input type="checkbox" value="思想政治" name="check_box_list"/>思想政治

    	<input type="checkbox" value="物理" name="check_box_list"/>物理

    	<input type="checkbox" value="生物" name="check_box_list"/>生物 -->

        <!-- <input type="submit" value="提交"> -->

        <!-- {% buttons %}
        <button name="submit" class="btn btn-primary">
            搜索
        </button>
        {% endbuttons %}

    </form> -->
    <!-- <input type="button"  onclick='display_alert()'/> -->
    <div class="form-group">
        <div class="checkbox">
          
            <form action="{% url 'career_find:result' 1 %}"  onsubmit="return test_ck(this)"  method="post">

              <div style="width:1000px;">
                <div style="width:700px;float:left;">
                  {% csrf_token %}
                  <!-- <div class='jumbotron'> -->

                    <span id='fz' style='font-size: 50px;padding-top:29px;' class="label label-default">请选择你的科目</span>
                  <!-- </div> -->
                  
                    <label class="checkbox-inline" style='padding-top:0px;position:relative;top:-20px;'>
                      <input id="inlineCheckbox1" type="checkbox" value="化学" name="check_box_list"/><span id='fz' >化学</span>
                    </label>
                    <label class="checkbox-inline" style='padding-top:0px;position:relative;top:-20px;'>
                      <input id="inlineCheckbox2" type="checkbox" value="历史" name="check_box_list"/><span id='fz'>历史</span>
                    </label>
                    <label class="checkbox-inline" style='padding-top:0px;position:relative;top:-20px;'>
                      <input id="inlineCheckbox3" type="checkbox" value="地理" name="check_box_list"/><span id='fz'>地理</span>
                    </label>

                    
                      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                    <label class="checkbox-inline" style='padding-top:0px;position:relative;top:-10px;'>
                      <input id="inlineCheckbox4" type="checkbox" value="思想政治" name="check_box_list"/><span id='fz'>政治</span>
                    </label>
                    <label class="checkbox-inline" style='padding-top:0px;position:relative;top:-10px;'>
                      <input id="inlineCheckbox5" type="checkbox" value="物理" name="check_box_list"/><span id='fz'>物理</span>
                    </label>
                    <label class="checkbox-inline" style='padding-top:0px;position:relative;top:-10px;'>
                      <input id="inlineCheckbox6" type="checkbox" value="生物" name="check_box_list"/><span id='fz'>生物</span>
                    
                  
                </div>
                <div style="width: 200px;float:left;">
                  {% buttons %}
                  <button name="submit"  class="btn btn-primary" style='margin-top:10px;position:relative;left:-50px;'>
                      <span>从这里开始</span>
                  </button>
                  {% endbuttons %}
                </div>

                <div style='clear:both;'><hr></div>

              </div>
                <!-- <button name="submit" class="btn btn-primary">
                    搜索
                </button> -->
            </form>
              <!-- <input type="button" value="提交" onclick='display_alert()'/> -->
        
        </div>
      </div>
    <div class='jumbotron'>
      <div class="container">
        <h1>找到为你量身打造的专业与学校！</h1>

        <p><b>欢迎你，<a href="#">{{ user.username }}</a>！</b>告诉我们你擅长的科目，我们将为你找到合适你的专业。</p>
          <a class="btn btn-primary btn-lg" role="button" href='http://www.zhcrc.com'>
          想要了解更多关于你的职业生涯？
          </a>
        </p>
      </div>
    </div>

  <div style="clear:both;text-align:center;"><hr>Copyright © 生涯大数据课题组  All Rights Reserved.</div>
</body>
</html>

career_find/templates/career_find/page.html
<!--         <span><a href="{% url 'career_find:page'  check_box=check_box page_num=contacts.page_number %}" >{{ contacts.number }}</a></span>
	 		<span><a href="{% url 'career_find:page'  check_box=check_box page_num=contacts.page_number %}" >{{ contacts.number }}</a></span> -->

career_find/templates/career_find/result.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>结果页</title>
    <style type="text/css">
        /*li {display:inline;font-family:"Times New Roman", Times, serif;
        font-size: 60px;}*/
        /*button {display:inline;}
        [name=check_box_list] {font-family:"Times New Roman", Times, serif;
                                font-size: 60px;}*/
        #fz {font-size: 20px;}
    </style>

    <script type="text/javascript">

      function test_ck( n ) {
      for ( var i = 0; i < n.check_box_list.length; ++i ) {
      if ( n.check_box_list[i].checked == true ) return true;
      }
      alert( '没有任何选项被选中' );
      return false;
      }

      var max_page = {{ contacts.paginator.num_pages }}
      function test_range( form ){
      if (form.跳页.value < 1 || form.跳页.value > max_page) {
              alert("请输入合理的页数!");
              form.跳页.focus();
              return false; }
      else if (isNaN(form.跳页.value)){
                alert("请输入数字!");
                form.跳页.focus();
                return false; }
         }

      display_alert = function ()
            {
              alert("I am an alert box!!");
            }
                </script>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>

  <body>

    <div class="container">
<!--   <script type="text/javascript">
  display_alert = function ()
            {
              alert("I am an alert box!!");
            }
  </script>
 -->
      <div class="form-group">
        <div class="checkbox">
          
            <form action="{% url 'career_find:result' 1 %}"  onsubmit="return test_ck(this)"  method="post">

              <div style="width:1000px;">
                <div style="width:700px;float:left;">
                  {% csrf_token %}
                  <!-- <div class='jumbotron'> -->
                    <span id='fz' style='font-size: 50px;padding-top:29px;' class="label label-default">请选择你的科目</span>
                  <!-- </div> -->
                  
                    <label class="checkbox-inline" style='padding-top:0px;position:relative;top:-20px;'>
                      <input id="inlineCheckbox1" type="checkbox" value="化学" name="check_box_list"/><span id='fz' >化学</span>
                    </label>
                    <label class="checkbox-inline" style='padding-top:0px;position:relative;top:-20px;'>
                      <input id="inlineCheckbox2" type="checkbox" value="历史" name="check_box_list"/><span id='fz'>历史</span>
                    </label>
                    <label class="checkbox-inline" style='padding-top:0px;position:relative;top:-20px;'>
                      <input id="inlineCheckbox3" type="checkbox" value="地理" name="check_box_list"/><span id='fz'>地理</span>
                    </label>

                    
                      &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                    <label class="checkbox-inline" style='padding-top:0px;position:relative;top:-10px;'>
                      <input id="inlineCheckbox4" type="checkbox" value="思想政治" name="check_box_list"/><span id='fz'>政治</span>
                    </label>
                    <label class="checkbox-inline" style='padding-top:0px;position:relative;top:-10px;'>
                      <input id="inlineCheckbox5" type="checkbox" value="物理" name="check_box_list"/><span id='fz'>物理</span>
                    </label>
                    <label class="checkbox-inline" style='padding-top:0px;position:relative;top:-10px;'>
                      <input id="inlineCheckbox6" type="checkbox" value="生物" name="check_box_list"/><span id='fz'>生物</span>
                    
                  
                </div>
                <div style="width: 200px;float:left;">
                  {% buttons %}
                  <button name="submit"  class="btn btn-primary" style='margin-top:10px;position:relative;left:-50px;'>
                      <span>查询</span>
                  </button>
                  {% endbuttons %}
                </div>

                <div style='clear:both;'><hr></div>

              </div>
                <!-- <button name="submit" class="btn btn-primary">
                    搜索
                </button> -->
            </form>
              <!-- <input type="button" value="提交" onclick='display_alert()'/> -->
        
        </div>
      </div>

    
    <p>
      <span class="glyphicon glyphicon-search"></span>

      <a href="{% url 'career_find:page' check_box='不限' page_num=1 %}">无要求</a>

    </p>

      <div class="table-responsive" >
        <table class="table table-striped table-bordered" >
          <tr>
            <th><b>地区</b></th>
            <th><b>学校代码</b></th>
            <th><b>学校名称</b></th>
            <th><b>层次</b></th>
            <th><b>专业类别</b></th>
            <th><b>专业</b></th>
            <th><b>科目要求</b></th>
            <th><b>学校网站</b></th>
            <th><b>适性</b></th>
          </tr>
      {% for result in contacts %}
          <tr>
            <td>{{ result.地区 }}</td>
            <td>{{ result.学校代码 }}</td>
            <td>{{ result.学校名称 }}</td>
            <td>{{ result.层次 }}</td>
            <td>{{ result.专业类别 }}</td>
            <td>{{ result.专业 }}</td>
            <td>{{ result.科目要求 }}</td>
            <td><a href={{ result.学校网站 }}  target = "_blank" >{{ result.学校网站 }}</a></td>
            <td>{{ result.coin }}</td>
          </tr>
      {% empty %}
          <tr>无结果</tr>
      {% endfor %} 
        </table>
      </div>
      <div style="width:1000px"> 
        <div class="pagination" style="width:820px;float:left;">
  <!--           <span class="step-links">
                

                
         		<span>
              -->
          <nav aria-label="Page navigation">   
         		<ul class="pagination">
              {% if  contacts.previous_page_number > 0 %}
                <li>
                  <a href="{% url 'career_find:page'   check_box=check_box page_num=contacts.previous_page_number %}" aria-label="Previous">
                    <span aria-hidden="true">«</span>
                  </a>
                </li>
              {% endif %}


                {% for page_num in page_list %}
                    {% if contacts.number == page_num %}
                        <li class="active" ><a href = ''>{{ contacts.number }}</a></li>
                    {% else %}
                        <li ><a href="{% url 'career_find:page' check_box=check_box page_num=page_num %}">{{ page_num }}</a></li>
                    {% endif %}
        		    {% endfor %}
                
                {% if contacts.has_next %}
                <li>
                  <a href="{% url 'career_find:page'  check_box=check_box page_num=contacts.next_page_number %}" aria-label="Next">
                    <span aria-hidden="true">»</span>
                  </a>
                </li>
                {% endif %}

            </ul>
          </nav>
        </div>
      		

              <!-- {% if contacts.has_previous %}
                  <a href="{% url 'career_find:page'   check_box=check_box page_num=contacts.previous_page_number %}">上一页</a>
                
              {% endif %}


              <span class="current">
                  第 {{ contacts.number }} / {{ contacts.paginator.num_pages }} 页
              </span>

              {% if contacts.has_next %}
                  <a href="{% url 'career_find:page'  check_box=check_box page_num=contacts.next_page_number %}" >下一页</a>
              {% endif %} -->
            
        <div class='form-group' style="width:180px;float:right;padding-top:40px;">
          <div style="width:180px">
              <form  class="form"  action= "{% url 'career_find:page' check_box=check_box page_num=1 %}" method='post' onsubmit='return test_range( this )'>
                {% csrf_token %}
                           
              <div style="width:54px;float:left;">
                <input name="跳页" class="form-control input-sm" type="text"  style="width:54px;height:35px" />
              </div>
              
              <div style="width:85px;float:left;text-align:center;padding-top:5px;">
                <span class="current" >
                  第 {{ contacts.number }} / {{ contacts.paginator.num_pages }} 页
                </span>
              </div>
              <div style="width:35px;float:left;">
                {% bootstrap_button "跳页" button_type="submit" button_class="btn-primary"  %}   
              </div>  
                  
  <!--                 
            {% buttons  %}
              <button name="submit" class="btn btn-primary" onclick="return test_range(this.form)">
                跳页
              </button>
            {% endbuttons %} -->               
            </form>
          </div>
        </div>
      </div>
      <div style="clear:both;text-align:center;"><hr>Copyright © 生涯大数据课题组  All Rights Reserved.</div>
    </div>


  </body>
</html>