career_find/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'career_find'

urlpatterns = [
    path('', views.index , name = 'index'),
    url(r'result/(?P<page_num>\d+)/', views.result , name = 'result'),
    url(r'result/(?P<check_box>.+)/(?P<page_num>\d+)/', views.page , name = 'page')
    # url(r'no_req/(?P<page_num>\d+)/', no_req , name = 'no_req')
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import login

from . import views

app_name = 'users'
urlpatterns = [
    # Login page.
    path('login/', login, {'template_name': 'users/login.html'},
        name='login'),
        
    # # Logout page.
    # path('logout/', views.logout_view, name='logout'),
    
    # # Registration page. 
    # path('register/', views.register, name='register'),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render

# Create your views here.

users/templates/users/login.html
{% load bootstrap3 %}

{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>高考选科查询系统</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>

  </head>
  
  <body>

  <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" style=""><h1 style='position:relative;bottom:20px;font-size:30px;'>欢迎使用高考选科查询系统</h1></a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <br>
          <!-- <ul class="nav navbar-nav">
            <li><i style='position:relative;bottom:-20px;font-size:5px;right:4px;'>2018-2018</i></li>
          </ul> -->
          
         <!--  <ul class="nav navbar-nav navbar-right">
            
          </ul> -->
        </div>
      </div>
  </nav>
  <div class="container">
    <div class="page-header">
        <h2>请先登录</h2>
    </div>
    <!-- <div>
      <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name="submit" class="btn btn-primary">登录</button>
        {% endbuttons %}
    
        <input type="hidden" name="next" value="{% url 'career_find:index' %}" />
      </form>
    </div>
 -->



    <div class="flex-center">
      <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                
                <form class="form" action="{% url 'users:login' %}" method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">登录</button>
                    <input type="hidden" name="next" value="{% url 'career_find:index' %}" />
                </form>
                <div class="flex-left top-gap text-small">
                    <div class="unit-2-3"><span>没有账号？<a href="http://www.psy.sdnu.edu.cn" target="_blank" style='position:relative;right:4px;top:0px;'>联系我们</a></span></div>
                    <!-- <div class="unit-1-3 flex-right"><span><a href="#">忘记密码？</a></span></div> -->
                </div>
            </div>
        </div>
      </div>
    </div>





    <div style="clear:both;text-align:center;"><hr>Copyright © 生涯大数据课题组  All Rights Reserved.</div>
  </div>

  </body>

</html>